version: '3' 

services:
    prometheus:
        image: prom/prometheus
        ports: 
            - 9090:9090
        volumes: 
            - ./prometheus/:/etc/prometheus/
        command: 
            - '--config.file=/etc/prometheus/prometheus.yml'
    
    node-exporter:
        image: prom/node-exporter
        depends_on: 
            - prometheus
        ports:
            - 9100:9100

    grafana:
        image: grafana/grafana
        depends_on: 
            - prometheus
        ports:
            - 3000:3000
        volumes: 
            - ./grafana:/etc/grafana/provisioning

    app:
        build: app
        ports:
            - 9091:9091
