global:
    scrape_interval:     15s
    evaluation_interval: 15s
  
rule_files:
    # - "first_rules.yml"
    # - "second_rules.yml"
  
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
      
    - job_name: 'node-exporter'
      static_configs:
      - targets: ['node-exporter:9100']

    - job_name: 'app'
      scrape_interval: 5s
      static_configs:
        - targets: ['app:9091']